Repository projectsyn/component-prometheus, pull requests merged in 2022-05, with the labels that each got.

#5 Add option to deploy secrets and Thanos sidecars
  .github/workflows/test.yaml
  .sync.yml
  class/defaults.yml
  component/common.libsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/thanos/syn-kube-prometheus/apps/syn-kube-prometheus.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/00_operator_namespace.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/01_secret_thanos-objstore-config-2.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/01_secret_thanos-objstore-config.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_0alertmanagerConfigCustomResourceDefinition.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_0alertmanagerCustomResourceDefinition.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_0podmonitorCustomResourceDefinition.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_0probeCustomResourceDefinition.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_0prometheusCustomResourceDefinition.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_0prometheusruleCustomResourceDefinition.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_0servicemonitorCustomResourceDefinition.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_0thanosrulerCustomResourceDefinition.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_clusterRole.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_clusterRoleBinding.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_deployment.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_prometheusRule.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_service.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_serviceAccount.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/10_prometheusOperator_serviceMonitor.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_clusterRole.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_clusterRoleBinding.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_podDisruptionBudget.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_prometheus.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_prometheusRule.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_prometheusRuleThanosSidecar.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_roleBindingConfig.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_roleBindingSpecificNamespaces.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_roleConfig.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_roleSpecificNamespaces.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_service.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_serviceAccount.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_serviceMonitor.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_serviceMonitorThanosSidecar.yaml
  tests/golden/thanos/syn-kube-prometheus/syn-kube-prometheus/20_test_prometheus_serviceThanosSidecar.yaml
  tests/thanos.yml
Labels: enhancement

#12 Add oauth2 proxy for authentication
  class/defaults.yml
  component/addons/oauth2-proxy.libsonnet
  docs/modules/ROOT/pages/how-tos/setup-keycloak.adoc
  docs/modules/ROOT/pages/references/addon-oauth2-proxy.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/oauth2-proxy/prometheus/apps/prometheus.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/00_namespace_default-instance.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/01_secret_oauth2-proxy.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_authIngress.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_authService.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_clusterRole.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_clusterRoleBinding.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_podDisruptionBudget.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_prometheus.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_roleBindingConfig.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_roleBindingSpecificNamespaces.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_roleConfig.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_roleSpecificNamespaces.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_service.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_serviceAccount.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_serviceMonitor.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_alertmanager.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_authIngress.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_authService.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_podDisruptionBudget.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_prometheusRule.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_secret.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_service.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_serviceAccount.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_serviceMonitor.yaml
  tests/oauth2-proxy.yml
Labels: enhancement

#14 Add how-to for deploying one or more Prometheus instances
  docs/modules/ROOT/pages/how-tos/prometheus.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#20 Remove nodeexporter-remove-mountpropagation addon
  component/addons/nodeexporter-remove-mountpropagation.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/kubernetes_1.20/prometheus/prometheus/50_default-instance_nodeExporter_daemonset.yaml
  tests/kubernetes_1.20.yml
Labels: ignore

#21 Allow Prometheus to scape Alertmanager and itself with oauth enabled
  component/addons/oauth2-proxy.libsonnet
  docs/modules/ROOT/pages/references/addon-oauth2-proxy.adoc
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_clusterRoleBindingProxy.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_clusterRoleProxy.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_prometheus.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_service.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_serviceMonitor.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_alertmanager.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_clusterRoleBindingProxy.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_clusterRoleProxy.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_service.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_serviceMonitor.yaml
Labels: enhancement

#22 Fix Prometheus to Alertmanager alert pushes with rbac/oidc enabled
  component/addons/oauth2-proxy.libsonnet
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_clusterRole.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_prometheus.yaml
Labels: ignore
