Repository projectsyn/component-prometheus, pull requests merged in 2022-06, with the labels that each got.

#24 OCP specific ServiceMonitors
  component/addons/openshift4-control-plane.libsonnet
  component/addons/openshift4.libsonnet
  tests/golden/openshift/prometheus/prometheus/20_default-instance_prometheus_roleBindingSpecificNamespaces.yaml
  tests/golden/openshift/prometheus/prometheus/20_default-instance_prometheus_roleSpecificNamespaces.yaml
  tests/golden/openshift/prometheus/prometheus/70_default-instance_kubernetesControlPlane_serviceMonitorCoreDNS.yaml
  tests/golden/openshift/prometheus/prometheus/70_default-instance_kubernetesControlPlane_serviceMonitorKubeControllerManager.yaml
  tests/golden/openshift/prometheus/prometheus/70_default-instance_kubernetesControlPlane_serviceMonitorKubeScheduler.yaml
  tests/openshift.yml
Labels: enhancement

#25 Add addon for nodeexporter on OpenShift
  component/addons/openshift4-nodeexporter.libsonnet
  component/addons/openshift4.libsonnet
  docs/modules/ROOT/pages/how-tos/openshift.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/openshift/prometheus/prometheus/00_namespace_default-instance.yaml
  tests/golden/openshift/prometheus/prometheus/50_default-instance_nodeExporter_daemonset.yaml
  tests/golden/openshift/prometheus/prometheus/50_default-instance_nodeExporter_securityContextConstraints.yaml
  tests/golden/openshift/prometheus/prometheus/50_default-instance_nodeExporter_securityContextRole.yaml
  tests/golden/openshift/prometheus/prometheus/50_default-instance_nodeExporter_securityContextRolebinding.yaml
  tests/golden/openshift/prometheus/prometheus/50_default-instance_nodeExporter_service.yaml
  tests/openshift.yml
Labels: enhancement

#26 Only restict Prometheus Operator to deploy to configured namespaces
  component/operator.libsonnet
  tests/golden/defaults/prometheus/prometheus/10_prometheusOperator_deployment.yaml
  tests/golden/kubernetes_1.20/prometheus/prometheus/10_prometheusOperator_deployment.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/10_prometheusOperator_deployment.yaml
  tests/golden/kubernetes_1.22/prometheus/prometheus/10_prometheusOperator_deployment.yaml
  tests/golden/multi/prometheus/prometheus/10_prometheusOperator_deployment.yaml
  tests/golden/openshift/prometheus/prometheus/10_prometheusOperator_deployment.yaml
  tests/golden/rewrite-registries/prometheus/prometheus/10_prometheusOperator_deployment.yaml
  tests/golden/thanos/prometheus/prometheus/10_prometheusOperator_deployment.yaml
Labels: change

#23 Update dependency quay.io/oauth2-proxy/oauth2-proxy to v7.3.0
  class/defaults.yml
Labels: dependency

#28 Update `.sync.yml` for latest modulesync template
  .sync.yml
Labels: ignore

#31 Add label selectors for monitors and rules
  component/addons/cluster-monitoring.libsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/how-tos/cluster-monitoring.adoc
  lib/prometheus.libsonnet
  tests/golden/cluster-monitoring/prometheus/prometheus/20_default-instance_prometheus_prometheus.yaml
  tests/golden/cluster-monitoring/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/cluster-monitoring/prometheus/prometheus/20_other_instance_prometheus_prometheus.yaml
  tests/golden/cluster-monitoring/prometheus/prometheus/20_other_instance_prometheus_prometheusRule.yaml
  tests/golden/kubernetes_1.20/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/kubernetes_1.20/prometheus/prometheus/30_default-instance_alertmanager_prometheusRule.yaml
  tests/golden/kubernetes_1.20/prometheus/prometheus/50_default-instance_nodeExporter_prometheusRule.yaml
  tests/golden/kubernetes_1.20/prometheus/prometheus/70_default-instance_kubernetesControlPlane_prometheusRule.yaml
  tests/golden/kubernetes_1.20/prometheus/prometheus/90_default-instance_kubeStateMetrics_prometheusRule.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/30_default-instance_alertmanager_prometheusRule.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/50_default-instance_nodeExporter_prometheusRule.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/70_default-instance_kubernetesControlPlane_prometheusRule.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/90_default-instance_kubeStateMetrics_prometheusRule.yaml
  tests/golden/kubernetes_1.22/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/kubernetes_1.22/prometheus/prometheus/30_default-instance_alertmanager_prometheusRule.yaml
  tests/golden/kubernetes_1.22/prometheus/prometheus/50_default-instance_nodeExporter_prometheusRule.yaml
  tests/golden/kubernetes_1.22/prometheus/prometheus/70_default-instance_kubernetesControlPlane_prometheusRule.yaml
  tests/golden/kubernetes_1.22/prometheus/prometheus/90_default-instance_kubeStateMetrics_prometheusRule.yaml
  tests/golden/multi/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/multi/prometheus/prometheus/20_other-instance_prometheus_prometheusRule.yaml
  tests/golden/multi/prometheus/prometheus/90_other-instance_kubeStateMetrics_prometheusRule.yaml
  tests/golden/openshift/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/openshift/prometheus/prometheus/30_default-instance_alertmanager_prometheusRule.yaml
  tests/golden/openshift/prometheus/prometheus/50_default-instance_nodeExporter_prometheusRule.yaml
  tests/golden/openshift/prometheus/prometheus/70_default-instance_kubernetesControlPlane_prometheusRule.yaml
  tests/golden/openshift/prometheus/prometheus/90_default-instance_kubeStateMetrics_prometheusRule.yaml
  tests/golden/rewrite-registries/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/rewrite-registries/prometheus/prometheus/30_default-instance_alertmanager_prometheusRule.yaml
  tests/golden/rewrite-registries/prometheus/prometheus/50_default-instance_nodeExporter_prometheusRule.yaml
  tests/golden/rewrite-registries/prometheus/prometheus/70_default-instance_kubernetesControlPlane_prometheusRule.yaml
  tests/golden/rewrite-registries/prometheus/prometheus/90_default-instance_kubeStateMetrics_prometheusRule.yaml
  tests/golden/thanos/prometheus/prometheus/20_test_prometheus_prometheusRule.yaml
  tests/golden/thanos/prometheus/prometheus/20_test_prometheus_prometheusRuleThanosSidecar.yaml
Labels: enhancement
