Repository projectsyn/component-prometheus, pull requests merged in 2022-10, with the labels that each got.

#54 Change image registry from k8s.gcr.io to registry.k8s.io
  class/defaults.yml
  tests/golden/additional_rules/prometheus/prometheus/80_default-instance_prometheusAdapter_deployment.yaml
  tests/golden/additional_rules/prometheus/prometheus/90_default-instance_kubeStateMetrics_deployment.yaml
  tests/golden/kubernetes_1.20/prometheus/prometheus/90_default-instance_kubeStateMetrics_deployment.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/80_default-instance_prometheusAdapter_deployment.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/90_default-instance_kubeStateMetrics_deployment.yaml
  tests/golden/kubernetes_1.22/prometheus/prometheus/80_default-instance_prometheusAdapter_deployment.yaml
  tests/golden/kubernetes_1.22/prometheus/prometheus/90_default-instance_kubeStateMetrics_deployment.yaml
  tests/golden/kubernetes_1.23/prometheus/prometheus/80_default-instance_prometheusAdapter_deployment.yaml
  tests/golden/kubernetes_1.23/prometheus/prometheus/90_default-instance_kubeStateMetrics_deployment.yaml
  tests/golden/kubernetes_1.24/prometheus/prometheus/80_default-instance_prometheusAdapter_deployment.yaml
  tests/golden/kubernetes_1.24/prometheus/prometheus/90_default-instance_kubeStateMetrics_deployment.yaml
  tests/golden/multi/prometheus/prometheus/80_default-instance_prometheusAdapter_deployment.yaml
  tests/golden/multi/prometheus/prometheus/90_other-instance_kubeStateMetrics_deployment.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_prometheus.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/20_default-instance_prometheus_prometheusRule.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_alertmanager.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_prometheusRule.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_secret.yaml
  tests/golden/openshift/prometheus/prometheus/80_default-instance_prometheusAdapter_deployment.yaml
  tests/golden/openshift/prometheus/prometheus/90_default-instance_kubeStateMetrics_deployment.yaml
Labels: dependency

#56 Mount Alertmanager ServiceAccount token for kube-rbac-proxy
  component/addons/oauth2-proxy.libsonnet
  tests/golden/additional_rules/prometheus/prometheus/70_default-instance_kubernetesControlPlane_prometheusRule.yaml
  tests/golden/kubernetes_1.21/prometheus/prometheus/70_default-instance_kubernetesControlPlane_prometheusRule.yaml
  tests/golden/oauth2-proxy/prometheus/prometheus/30_default-instance_alertmanager_serviceAccount.yaml
  tests/golden/rewrite-registries/prometheus/prometheus/70_default-instance_kubernetesControlPlane_prometheusRule.yaml
Labels: bug

#60 Add option to pick up Rules, Monitors and Probes from any namespace
  class/defaults.yml
  component/addons/cluster-monitoring.libsonnet
  docs/modules/ROOT/pages/how-tos/cluster-monitoring.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement
